# coding=utf-8
#***************************************************************
# Author     : John
# Created on : 2025-12-22
# Description: 社区健康5G 信创1.0 - 表与表
# 需求：/Users/linghuchong/Desktop/智赢健康/信创/患者主索引_评估表.png
#***************************************************************
from PO.SqlserverPO import *
Sqlserver_PO = SqlserverPO("192.168.0.234", "sa", "Zy_123456789", "CHC", "utf8")

SFZH = "310110196604033216"

# todo 患者主索引表
TB_EMPI_INDEX_ROOT = Sqlserver_PO.select("SELECT * FROM TB_EMPI_INDEX_ROOT where IDCARDNO='%s'" % (SFZH))
print("TB_EMPI_INDEX_ROOT =>", TB_EMPI_INDEX_ROOT)
print("TB_EMPI_INDEX_ROOT[0]['IDCARDNO'] =>", TB_EMPI_INDEX_ROOT[0]['IDCARDNO'])
print("TB_EMPI_INDEX_ROOT[0]['GUID'] =>", TB_EMPI_INDEX_ROOT[0]['GUID'])

# todo 封面表
HRCOVER = Sqlserver_PO.select("SELECT * FROM HRCOVER where ARCHIVENUM='%s'" % (TB_EMPI_INDEX_ROOT[0]['IDCARDNO']))
print("HRCOVER =>", HRCOVER)

# todo 基本信息表
HRPERSONBASICINFO = Sqlserver_PO.select("SELECT * FROM HRPERSONBASICINFO where ARCHIVENUM='%s'" % (TB_EMPI_INDEX_ROOT[0]['IDCARDNO']))
print("HRPERSONBASICINFO =>", HRPERSONBASICINFO)
print("HRPERSONBASICINFO[0]['ID'] =>", HRPERSONBASICINFO[0]['ID'])

# todo 多选表（外键错误）???
# HRASSOCIATIONINFO = Sqlserver_PO.select("SELECT * FROM HRASSOCIATIONINFO where ?='%s'" % (HRPERSONBASICINFO[0]['ID']))
# print("HRASSOCIATIONINFO =>", HRASSOCIATIONINFO)

# todo 体检信息表
TB_DC_EXAMINATION_INFO = Sqlserver_PO.select("SELECT * FROM TB_DC_EXAMINATION_INFO where EMPIGUID='%s'" % (TB_EMPI_INDEX_ROOT[0]['GUID']))
print("TB_DC_EXAMINATION_INFO =>", TB_DC_EXAMINATION_INFO)
print("TB_DC_EXAMINATION_INFO[0]['GUID'] =>", TB_DC_EXAMINATION_INFO[0]['GUID'])
print("TB_DC_EXAMINATION_INFO[0]['EXAMINATIONID'] =>", TB_DC_EXAMINATION_INFO[0]['EXAMINATIONID'])
print("TB_DC_EXAMINATION_INFO[0]['ORGCODE'] =>", TB_DC_EXAMINATION_INFO[0]['ORGCODE'])

# # todo 职业暴露史信息表（没有外键链接）？？？
# TB_DC_EXAMINATION_EXPOSURE = Sqlserver_PO.select("SELECT * FROM TB_DC_EXAMINATION_EXPOSURE where ？='%s'" % (TB_DC_EXAMINATION_INFO[0]['GUID']))
# print("TB_DC_EXAMINATION_EXPOSURE =>", TB_DC_EXAMINATION_EXPOSURE)

# # todo 体检检验结果表
TB_DC_EXAMINATION_LIS = Sqlserver_PO.select("SELECT * FROM TB_DC_EXAMINATION_LIS where EXAMINATION_ID='%s' and YLJGDM='%s'" % (TB_DC_EXAMINATION_INFO[0]['EXAMINATIONID'], TB_DC_EXAMINATION_INFO[0]['ORGCODE']))
print("TB_DC_EXAMINATION_LIS =>", TB_DC_EXAMINATION_LIS)


# # todo 儿童基本情况信息表
SFZH = '410101202308070009'
# TB_CHILD_MAIN = Sqlserver_PO.select("SELECT * FROM TB_CHILD_MAIN where CARD_NO='%s'" % (TB_EMPI_INDEX_ROOT[0]['IDCARDNO']))
TB_CHILD_MAIN = Sqlserver_PO.select("SELECT * FROM TB_CHILD_MAIN where CARD_NO='%s'" % (SFZH))
print("TB_CHILD_MAIN =>", TB_CHILD_MAIN)
print("TB_CHILD_MAIN[0]['CHILD_ID'] =>", TB_CHILD_MAIN[0]['CHILD_ID'])

# # todo 儿童体检记录表
TB_CHILD_EXAMINATION = Sqlserver_PO.select("SELECT * FROM TB_CHILD_EXAMINATION where CHILDMAINID='%s'" % (TB_CHILD_MAIN[0]['CHILD_ID']))
print("TB_CHILD_EXAMINATION =>", TB_CHILD_EXAMINATION)

# # todo 慢性病防治信息表
TB_DC_CHRONIC_INFO = Sqlserver_PO.select("SELECT * FROM TB_DC_CHRONIC_INFO where EMPIGUID='%s'" % (TB_EMPI_INDEX_ROOT[0]['GUID']))
print("TB_DC_CHRONIC_INFO =>", TB_DC_CHRONIC_INFO)
print("TB_DC_CHRONIC_INFO[0]['MANAGENUM'] =>", TB_DC_CHRONIC_INFO[0]['MANAGENUM'])
print("TB_DC_CHRONIC_INFO[0]['ORGCODE'] =>", TB_DC_CHRONIC_INFO[0]['ORGCODE'])
print("TB_DC_CHRONIC_INFO[0]['EMPIGUID'] =>", TB_DC_CHRONIC_INFO[0]['EMPIGUID'])

# # todo 慢性病防治随访主表
TB_DC_CHRONIC_MAIN = Sqlserver_PO.select("SELECT * FROM TB_DC_CHRONIC_MAIN where MANAGENUM='%s' and ORGCODE='%s'" % (TB_DC_CHRONIC_INFO[0]['MANAGENUM'], TB_DC_CHRONIC_INFO[0]['ORGCODE']))
print("TB_DC_CHRONIC_MAIN =>", TB_DC_CHRONIC_MAIN)


# # todo 糖尿病随访表
TB_DC_DM_VISIT = Sqlserver_PO.select("SELECT * FROM TB_DC_DM_VISIT where EMPIGUID='%s' " % (TB_DC_CHRONIC_INFO[0]['EMPIGUID']))
print("TB_DC_DM_VISIT =>", TB_DC_DM_VISIT)

# # todo 高血压随访表
TB_DC_HTN_VISIT = Sqlserver_PO.select("SELECT * FROM TB_DC_HTN_VISIT where EMPIGUID='%s' " % (TB_DC_CHRONIC_INFO[0]['EMPIGUID']))
print("TB_DC_HTN_VISIT =>", TB_DC_HTN_VISIT)

# # todo 高血压筛查测压记录
TB_HTN_MEASUREMENT_RECORD = Sqlserver_PO.select("SELECT * FROM TB_HTN_MEASUREMENT_RECORD where ZJHM='%s' " % (TB_EMPI_INDEX_ROOT[0]['IDCARDNO']))
print("TB_HTN_MEASUREMENT_RECORD =>", TB_HTN_MEASUREMENT_RECORD)


# # todo 糖尿病前期随访表
TB_DM_EARLY_VISIT = Sqlserver_PO.select("SELECT * FROM TB_DM_EARLY_VISIT where ZJHM='%s' " % (TB_EMPI_INDEX_ROOT[0]['IDCARDNO']))
print("TB_DM_EARLY_VISIT =>", TB_DM_EARLY_VISIT)
# # todo 糖尿病筛查登记表
TB_DM_SCREENING = Sqlserver_PO.select("SELECT * FROM TB_DM_SCREENING where ZJHM='%s' " % (TB_EMPI_INDEX_ROOT[0]['IDCARDNO']))
print("TB_DM_SCREENING =>", TB_DM_SCREENING)
# # todo 高血压易患随访表
TB_HTN_EASILY_VISIT = Sqlserver_PO.select("SELECT * FROM TB_HTN_EASILY_VISIT where ZJHM='%s' " % (TB_EMPI_INDEX_ROOT[0]['IDCARDNO']))
print("TB_HTN_EASILY_VISIT =>", TB_HTN_EASILY_VISIT)
# # todo 35岁首诊测压报卡
TB_35_FIRSTBP = Sqlserver_PO.select("SELECT * FROM TB_35_FIRSTBP where ZJHM='%s' " % (TB_EMPI_INDEX_ROOT[0]['IDCARDNO']))
print("TB_35_FIRSTBP =>", TB_35_FIRSTBP)


# # todo 居民血糖测量表
TB_PATIENT_BLD_GLUCOSE = Sqlserver_PO.select("SELECT * FROM TB_PATIENT_BLD_GLUCOSE where personcard='%s' " % (TB_EMPI_INDEX_ROOT[0]['IDCARDNO']))
print("TB_PATIENT_BLD_GLUCOSE =>", TB_PATIENT_BLD_GLUCOSE)
# # todo 居民血压测量表
TB_PATIENT_BLD_PRESSURE = Sqlserver_PO.select("SELECT * FROM TB_PATIENT_BLD_PRESSURE where personcard='%s' " % (TB_EMPI_INDEX_ROOT[0]['IDCARDNO']))
print("TB_PATIENT_BLD_PRESSURE =>", TB_PATIENT_BLD_PRESSURE)
# # todo 居民身高体重测量表
TB_PATIENT_HEIGHT = Sqlserver_PO.select("SELECT * FROM TB_PATIENT_HEIGHT where personcard='%s' " % (TB_EMPI_INDEX_ROOT[0]['IDCARDNO']))
print("TB_PATIENT_HEIGHT =>", TB_PATIENT_HEIGHT)
# # todo 患者腰围臀围测量表
TB_PATIENT_WAIST = Sqlserver_PO.select("SELECT * FROM TB_PATIENT_WAIST where personcard='%s' " % (TB_EMPI_INDEX_ROOT[0]['IDCARDNO']))
print("TB_PATIENT_WAIST =>", TB_PATIENT_WAIST)
# # todo 中医药体质表
TB_DC_MEDICIANE = Sqlserver_PO.select("SELECT * FROM TB_DC_MEDICIANE where IDCARD='%s' " % (TB_EMPI_INDEX_ROOT[0]['IDCARDNO']))
print("TB_DC_MEDICIANE =>", TB_DC_MEDICIANE)
# # todo 屈光检查表
TB_DIOPTOMETRY = Sqlserver_PO.select("SELECT * FROM TB_DIOPTOMETRY where idCardNo='%s' " % (TB_EMPI_INDEX_ROOT[0]['IDCARDNO']))
print("TB_DIOPTOMETRY =>", TB_DIOPTOMETRY)



# # # todo 门诊就诊记录表 (无数据)
# TB_HIS_OP_MEDICAL_RECORD = Sqlserver_PO.select("SELECT * FROM TB_HIS_OP_MEDICAL_RECORD where EMPIGUID='%s' " % (TB_EMPI_INDEX_ROOT[0]['GUID']))
# print("TB_HIS_OP_MEDICAL_RECORD =>", TB_HIS_OP_MEDICAL_RECORD)
# print("TB_HIS_OP_MEDICAL_RECORD[0]['OPVISITSTRNO'] =>", TB_HIS_OP_MEDICAL_RECORD[0]['OPVISITSTRNO'])
# print("TB_HIS_OP_MEDICAL_RECORD[0]['ORGCODE'] =>", TB_HIS_OP_MEDICAL_RECORD[0]['ORGCODE'])
#
# # # todo 门诊处方表
# TB_HIS_OP_PERSCRIPTION = Sqlserver_PO.select("SELECT * FROM TB_HIS_OP_PERSCRIPTION where OPVISITSTRNO='%s' and ORGCODE='%s' " % (TB_HIS_OP_MEDICAL_RECORD[0]['OPVISITSTRNO'],TB_HIS_OP_MEDICAL_RECORD[0]['ORGCODE']))
# print("TB_HIS_OP_PERSCRIPTION =>", TB_HIS_OP_PERSCRIPTION)

# # # todo 住院记录表（无数据）
# TB_HIS_IP_MEDICAL_RECORD = Sqlserver_PO.select("SELECT * FROM TB_HIS_IP_MEDICAL_RECORD where EMPIGUID='%s' " % (TB_EMPI_INDEX_ROOT[0]['GUID']))
# print("TB_HIS_IP_MEDICAL_RECORD =>", TB_HIS_IP_MEDICAL_RECORD)
# print("TB_HIS_IP_MEDICAL_RECORD[0]['IPVISITSTRNO'] =>", TB_HIS_IP_MEDICAL_RECORD[0]['IPVISITSTRNO'])
# print("TB_HIS_IP_MEDICAL_RECORD[0]['ORGCODE'] =>", TB_HIS_IP_MEDICAL_RECORD[0]['ORGCODE'])
#
# # # # todo 住院遗嘱表
# TB_HIS_IP_ORDER = Sqlserver_PO.select("SELECT * FROM TB_HIS_IP_ORDER where IPVISITSTRNO='%s' and ORGCODE='%s' " % (TB_HIS_IP_MEDICAL_RECORD[0]['IPVISITSTRNO'],TB_HIS_IP_MEDICAL_RECORD[0]['ORGCODE']))
# print("TB_HIS_IP_ORDER =>", TB_HIS_IP_ORDER)


# # # todo 孕产妇信息表
ZJHM = '310105201612020089'
TB_PREGNANT_MAIN_INFO = Sqlserver_PO.select("SELECT * FROM TB_PREGNANT_MAIN_INFO where ZJHM='%s' " % (ZJHM))
# TB_PREGNANT_MAIN_INFO = Sqlserver_PO.select("SELECT * FROM TB_PREGNANT_MAIN_INFO where ZJHM='%s' " % (TB_EMPI_INDEX_ROOT[0]['IDCARDNO']))
print("TB_PREGNANT_MAIN_INFO =>", TB_PREGNANT_MAIN_INFO)
print("TB_PREGNANT_MAIN_INFO[0]['YCFID'] =>", TB_PREGNANT_MAIN_INFO[0]['YCFID'])

# # # todo 分娩记录表
TB_CHILDBIRTH_RECORD = Sqlserver_PO.select("SELECT * FROM TB_CHILDBIRTH_RECORD where YCFID='%s' " % (TB_PREGNANT_MAIN_INFO[0]['YCFID']))
print("TB_CHILDBIRTH_RECORD =>", TB_CHILDBIRTH_RECORD)

# # # todo 产前随访信息表
TB_PRENATAL_VISIT = Sqlserver_PO.select("SELECT * FROM TB_PRENATAL_VISIT where YCFID='%s' " % (TB_PREGNANT_MAIN_INFO[0]['YCFID']))
print("TB_PRENATAL_VISIT =>", TB_PRENATAL_VISIT)

# # # todo 产后访视记录表
TB_POSTPARTUM_VISIT_RECORD = Sqlserver_PO.select("SELECT * FROM TB_POSTPARTUM_VISIT_RECORD where YCFID='%s' " % (TB_PREGNANT_MAIN_INFO[0]['YCFID']))
print("TB_POSTPARTUM_VISIT_RECORD =>", TB_POSTPARTUM_VISIT_RECORD)



# todo 签约信息表
QYYH = Sqlserver_PO.select("SELECT * FROM QYYH where SFZH='%s' " % (TB_EMPI_INDEX_ROOT[0]['IDCARDNO']))
print("QYYH =>", QYYH)
print("QYYH[0]['SFZH'] =>", QYYH[0]['SFZH'])
# todo 重点人群编码 IMPORTANT_CATEGORY
# todo 健康服务信息表 T_HEALTH_SERVICE


# # # todo 评估表
SFZH = '310110195303082052'
# T_ASSESS_INFO = Sqlserver_PO.select("SELECT * FROM T_ASSESS_INFO where ID_CARD='%s' " % (QYYH[0]['SFZH']))
T_ASSESS_INFO = Sqlserver_PO.select("SELECT * FROM T_ASSESS_INFO where ID_CARD='%s' " % (SFZH))
print("T_ASSESS_INFO =>", T_ASSESS_INFO)
print("T_ASSESS_INFO[0]['MODEL_CODE'] =>", T_ASSESS_INFO[0]['MODEL_CODE'])
print("T_ASSESS_INFO[0]['ID'] =>", T_ASSESS_INFO[0]['ID'])


# todo 报告模版信息表
MODEL_INFO = Sqlserver_PO.select("SELECT * FROM MODEL_INFO where MODEL_CODE='%s' " % (T_ASSESS_INFO[0]['MODEL_CODE']))
print("MODEL_INFO =>", MODEL_INFO)
print("MODEL_INFO[0]['ID'] =>", MODEL_INFO[0]['ID'])

# todo 机构模版表
ORG_MODEL_INFO = Sqlserver_PO.select("SELECT * FROM ORG_MODEL_INFO where MODEL_ID='%s' " % (MODEL_INFO[0]['ID']))
print("ORG_MODEL_INFO =>", ORG_MODEL_INFO)

# todo 评估流程表
T_ASSESS_PROCESS = Sqlserver_PO.select("SELECT * FROM T_ASSESS_PROCESS where ASSESS_ID='%s' " % (T_ASSESS_INFO[0]['ID']))
print("T_ASSESS_PROCESS =>", T_ASSESS_PROCESS)

# todo 评估规则结果表
T_ASSESS_RULE_RECORD = Sqlserver_PO.select("SELECT * FROM T_ASSESS_RULE_RECORD where ASSESS_ID='%s' " % (T_ASSESS_INFO[0]['ID']))
print("T_ASSESS_RULE_RECORD =>", T_ASSESS_RULE_RECORD)

# todo 单基本规则命中日志
T_SINGLE_DISEASE_LOG = Sqlserver_PO.select("SELECT * FROM T_SINGLE_DISEASE_LOG where ASSESS_ID='%s' " % (T_ASSESS_INFO[0]['ID']))
print("T_SINGLE_DISEASE_LOG =>", T_SINGLE_DISEASE_LOG)

# todo 健康评估率统计表
T_ASSESS_STATISTICS = Sqlserver_PO.select("SELECT * FROM T_ASSESS_STATISTICS where ASSESS_ID='%s' " % (T_ASSESS_INFO[0]['ID']))
print("T_ASSESS_STATISTICS =>", T_ASSESS_STATISTICS)



# todo 评估指标表
T_ASSESS_INDEX_INFO = Sqlserver_PO.select("SELECT * FROM T_ASSESS_INDEX_INFO where ASSESS_ID='%s' " % (T_ASSESS_INFO[0]['ID']))
print("T_ASSESS_INDEX_INFO =>", T_ASSESS_INDEX_INFO)
# todo 儿童评估检查表
T_ASSESS_CHILD_EXAMINATION = Sqlserver_PO.select("SELECT * FROM T_ASSESS_CHILD_EXAMINATION where ASSESS_ID='%s' " % (T_ASSESS_INFO[0]['ID']))
print("T_ASSESS_CHILD_EXAMINATION =>", T_ASSESS_CHILD_EXAMINATION)
# todo 孕产妇信息表——评估
T_ASSESS_MATERNAL = Sqlserver_PO.select("SELECT * FROM T_ASSESS_MATERNAL where ASSESS_ID='%s' " % (T_ASSESS_INFO[0]['ID']))
print("T_ASSESS_MATERNAL =>", T_ASSESS_MATERNAL)
# todo 学生屈光检查信息表
T_ASSESS_DIOPTOMETRY = Sqlserver_PO.select("SELECT * FROM T_ASSESS_DIOPTOMETRY where ASSESS_ID='%s' " % (T_ASSESS_INFO[0]['ID']))
print("T_ASSESS_DIOPTOMETRY =>", T_ASSESS_DIOPTOMETRY)


# todo 评估医疗信息表
T_ASSESS_MEDICAL_INFO = Sqlserver_PO.select("SELECT * FROM T_ASSESS_MEDICAL_INFO where ASSESS_ID='%s' " % (T_ASSESS_INFO[0]['ID']))
print("T_ASSESS_MEDICAL_INFO =>", T_ASSESS_MEDICAL_INFO)
# todo 门诊数据
ASSESS_DIAGNOSIS = Sqlserver_PO.select("SELECT * FROM ASSESS_DIAGNOSIS where ASSESS_ID='%s' " % (T_ASSESS_INFO[0]['ID']))
print("ASSESS_DIAGNOSIS =>", ASSESS_DIAGNOSIS)
# todo 评估既往史表
T_ASSESS_PREVIOUS_HISTORY = Sqlserver_PO.select("SELECT * FROM T_ASSESS_PREVIOUS_HISTORY where ASSESS_ID='%s' " % (T_ASSESS_INFO[0]['ID']))
print("T_ASSESS_PREVIOUS_HISTORY =>", T_ASSESS_PREVIOUS_HISTORY)
# todo 评估家族史表
T_ASSESS_FAMILY_HISTORY = Sqlserver_PO.select("SELECT * FROM T_ASSESS_FAMILY_HISTORY where ASSESS_ID='%s' " % (T_ASSESS_INFO[0]['ID']))
print("T_ASSESS_FAMILY_HISTORY =>", T_ASSESS_FAMILY_HISTORY)
# todo 过敏史表
T_ASSESS_ALLERGY = Sqlserver_PO.select("SELECT * FROM T_ASSESS_ALLERGY where ASSESS_ID='%s' " % (T_ASSESS_INFO[0]['ID']))
print("T_ASSESS_ALLERGY =>", T_ASSESS_ALLERGY)
# todo 疫苗接种情况表
T_ASSESS_VICCINE = Sqlserver_PO.select("SELECT * FROM T_ASSESS_VICCINE where ASSESS_ID='%s' " % (T_ASSESS_INFO[0]['ID']))
print("T_ASSESS_VICCINE =>", T_ASSESS_VICCINE)
# todo 检验情况快照表
T_INSPECTION_SNAPSHOT = Sqlserver_PO.select("SELECT * FROM T_INSPECTION_SNAPSHOT where ASSESS_ID='%s' " % (T_ASSESS_INFO[0]['ID']))
print("T_INSPECTION_SNAPSHOT =>", T_INSPECTION_SNAPSHOT)
# todo 评估检验结果表
T_ASSESS_INFO_REPORT_INDICATOR = Sqlserver_PO.select("SELECT * FROM T_ASSESS_INFO_REPORT_INDICATOR where ASSESS_ID='%s' " % (T_ASSESS_INFO[0]['ID']))
print("T_ASSESS_INFO_REPORT_INDICATOR =>", T_ASSESS_INFO_REPORT_INDICATOR)
# todo 其它辅助检查快照表
T_ASSIST_CHECKING_SNAPSHOTS = Sqlserver_PO.select("SELECT * FROM T_ASSIST_CHECKING_SNAPSHOTS where ASSESS_ID='%s' " % (T_ASSESS_INFO[0]['ID']))
print("T_ASSIST_CHECKING_SNAPSHOTS =>", T_ASSIST_CHECKING_SNAPSHOTS)

#
# # # # todo 评估结果报告表
# T_ASSESS_REPORT = Sqlserver_PO.select("SELECT * FROM T_ASSESS_REPORT where ASSESS_ID='%s' " % (T_ASSESS_INFO[0]['ID']))
# print("T_ASSESS_REPORT =>", T_ASSESS_REPORT)
# # todo 评估疾病组规则表 T_RULE_GROUP
# # todo 评估规则表 T_RULE
# # todo 健康干预配置表 T_INTERVENE_CONFIG
# # todo 评估建议模版表 T_INTERVENE_TEMPLATE
#
# # # # todo 评估用药表
# T_ASSESS_DRUG = Sqlserver_PO.select("SELECT * FROM T_ASSESS_DRUG where ASSESS_ID='%s' " % (T_ASSESS_INFO[0]['ID']))
# print("T_ASSESS_DRUG =>", T_ASSESS_DRUG)
#
# # # # todo 评估检验数据表
# T_ASSESS_INFO_REPORT = Sqlserver_PO.select("SELECT * FROM T_ASSESS_INFO_REPORT where ASSESS_ID='%s' " % (T_ASSESS_INFO[0]['ID']))
# print("T_ASSESS_INFO_REPORT =>", T_ASSESS_INFO_REPORT)
# # todo 检验值code映射表 SOURCE_ITEM_CODE
#
# # todo 评估用药情况表
# ASSESS_MEDICATION = Sqlserver_PO.select("SELECT * FROM ASSESS_MEDICATION where ASSESS_ID='%s' " % (T_ASSESS_INFO[0]['ID']))
# print("ASSESS_MEDICATION =>", ASSESS_MEDICATION)
#
# # todo 评估风险因素表
# T_ASSESS_FACTOR = Sqlserver_PO.select("SELECT * FROM T_ASSESS_FACTOR where ASSESS_ID='%s' " % (T_ASSESS_INFO[0]['ID']))
# print("T_ASSESS_FACTOR =>", T_ASSESS_FACTOR)
#
# # todo 评估已患疾病表
# T_ASSESS_DISEASE = Sqlserver_PO.select("SELECT * FROM T_ASSESS_DISEASE where ASSESS_ID='%s' " % (T_ASSESS_INFO[0]['ID']))
# print("T_ASSESS_DISEASE =>", T_ASSESS_DISEASE)
# # todo ICD诊断编码对照表 SOURCE_ICD
# # todo 疾病code_name映射表 DISEASE_MAPPING
